<script lang="ts">
  import { address as addressmodule, networks } from 'liquidjs-lib';
  import { assetsStore } from '../../stores/assets.store';
  import { contractStore } from '../../stores/contract.store';
  import { marinaStore } from '../../stores/marina.store';
  import classNames from 'classnames';

  export let address: string;
  export let asset: string;
  export let isBurn: boolean;
  export let isFee: boolean;

  export let satoshis: number;
  let amount: number;
  let useChangeAddress = false;
  let marinaNexChangeAddress: string;

  async function setChangeAddress() {
    if (marinaNexChangeAddress) return;
    marinaNexChangeAddress = (await $marinaStore.provider.getNextChangeAddress()).confidentialAddress;
  }

  function isConfidentialAddress(addr) {
    try {
      return addressmodule.isConfidential(addr);
    } catch {
      return false;
    }
  }

  $: isConfidentialAddr = isConfidentialAddress(address);
  $: assetDetails = $assetsStore.get(asset);
  $: hasFeeOutput = $contractStore.tx.pset.outputs.findLast(o => o.script.length === 0) !== undefined;
</script>

<div class="field">
  <div class="control">
    <label class="checkbox">
      <input 
        disabled={hasFeeOutput || isBurn || useChangeAddress} 
        type="checkbox" 
        bind:checked={isFee}
        on:input={() => {
          if (!isFee) {
            asset = networks[$marinaStore.network].assetHash
          }
        }}
      />
      I want to add the fee output
    </label>
  </div>
  {#if hasFeeOutput}
    <p class="help is-info">Disabled, fee output already added</p>
  {/if}
</div>

<div class="field">
    <div class="control">
    <label class="checkbox">
      <input 
        disabled={isFee || isBurn} 
        type="checkbox" 
        bind:checked={useChangeAddress}
        on:input={() => {
          if (!useChangeAddress) {
            setChangeAddress().then(() => {
              address = marinaNexChangeAddress;
            })
          } else {
            address = '';
          }
        }}
      />
      I want to create a change output
    </label>
  </div>
</div>

<div class="field">
  <div class="control">
    <label class="checkbox">
      <input disabled={isFee || useChangeAddress} type="checkbox" bind:checked={isBurn} />
      I want to burn assets
    </label>
  </div>
</div>

<div class="field">
  <label for="liquidaddress" class="label">Address</label>
  <div class="control">
    <input
      id="liquidaddress"
      class="input"
      readonly={useChangeAddress}
      type="text"
      placeholder="tlq1...."
      disabled={isBurn || isFee}
      bind:value={address}
    />
  </div>
  {#if useChangeAddress}
    <p class="help is-info">
      This address has been generated by Marina
    </p>
  {/if}
  {#if isConfidentialAddr}
    <p class="help is-info">
      This address is confidential, output will be blinded
    </p>
  {/if}
</div>

<div class="field">
  <label for="asset" class="label">Asset</label>
  <div class="control">
    <div class="select">
      <select disabled={isFee} id="asset" bind:value={asset}>
        {#each $assetsStore.assets as asset}
          <option value={asset.assetHash}>{asset.ticker}</option>
        {/each}
      </select>
    </div>
  </div>
</div>

<div class="field">
  <label for="amount" class="label">Amount</label>
  <div class="control">
    <input
      disabled={!assetDetails}
      id="amount"
      class="input"
      type="number"
      placeholder="0.0021"
      bind:value={amount}
      on:input={() => (satoshis = Math.round(amount * 10 ** assetDetails.precision))}
    />
  </div>
  {#if !assetDetails}
    <p class="help is-info">Select asset first</p>
  {/if}
  {#if satoshis}
    <p class="help is-info">This is equivalent to {satoshis} satoshis (precision {assetDetails.precision})</p>
  {/if}
</div>
